### ISSUE TITLE
Looping the same articles that are listed

### ISSUE THREAD

**Issue by rickyedwards86** [apedestrian/infinite-scroll-block#1]
This is a great plugin but seems to loop over the same set of articles that are currently displayed

**Comment by aPEDESTRIAN** [comment]
Interesting; I've had the plugin run on half a dozen different sites but haven't seen this bug before.
Can you give me a list of other plugins you are using, what theme is active, and which template was being displayed so I can try to reproduce it?

**Comment by aPEDESTRIAN** [comment]
No response and no instructions to reproduce issue; chalking it up to user error
